name: future_queue
description: Dart package which provides sequential future execution with return values.
version: 0.0.1
repository: https://github.com/rorystephenson/future_queue

environment:
  sdk: ">=2.10.4 <3.0.0"

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.3
  pedantic: ^1.9.2
