name: future_queue
description: Dart package which provides sequential future execution with return values.
version: 0.1.0
repository: https://github.com/rorystephenson/future_queue

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.1
  pedantic: ^1.11.0
